# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoordinateExtractor_dev1
                                 A QGIS plugin
 Extract coordinate form raw text
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-03
        copyright            : (C) 2019 by a
        email                : a
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoordinateExtractor_dev1 class from file CoordinateExtractor_dev1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .coord_extractor import CoordinateExtractor_dev1
    return CoordinateExtractor_dev1(iface)
