# -*- coding: utf-8 -*-
"""
/***************************************************************************
 csv2shp
                                 A QGIS plugin
 csv2shp
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-16
        copyright            : (C) 2019 by csv2shp
        email                : csv2shp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load csv2shp class from file csv2shp.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .csv2shp import csv2shp
    return csv2shp(iface)
